server {
    server_name binance.globalhostia.com;
    
    location /messages {
        proxy_pass         http://127.0.0.1:8765;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   Authorization $http_authorization;
        proxy_buffering    off;
        proxy_cache        off;
    }
    
    location /health {
        proxy_pass http://127.0.0.1:8765;
    }
    
    location / {
        return 404;
    }
    
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/binance.globalhostia.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/binance.globalhostia.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = binance.globalhostia.com) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    server_name binance.globalhostia.com;
    return 404;
}
